### PR TITLE
Use FOFGroupIDs from separate file

### PR DESCRIPTION
**Pull request by robjmcgibbon**
For the FLAMINGO HYDRO runs the definition of FOF changed since the simulation was originally run. Therefore the FOF IDs in the snapshots do not correspond to the FOF IDs used to run HBT. Currently two properties in SOAP require FOF IDs - MassFractionSatellite and MassFractionExternal, so we need the updated IDs for these calculations.

This PR allows for a separate snapshot file containing FOF IDs to be passed to SOAP. These are then saved to the group membership files. When the group membership files are read in the FOF IDs from the original snapshots will be overwritten by the new values. 

An alternative implementation would be to allow for multiple "extra-input" files to be passed, e.g. we would pass both the group membership files and the new FOF files when running compute_halo_properties.py. I implemented it this way since the new FOF snapshots do not have the same order as the original snapshots, and it is easy to sort them as part of group_membership.py. I also think it's worth having a saved copy of the new FOF IDs, which this allows us to do.

### CODE REVIEW

**Comment by jchelly** [comment]
Just to check that I understand why this is necessary: HBT can run on the new snapshot files generated by the FoF code (e.g. /cosma8/data/dp004/jlvc76/FLAMINGO/FOF/L2800N5040/HYDRO_FIDUCIAL/fof_snapshot), but we can't run SOAP on those same snapshots because not all particle properties are present. Is that correct?

I think the reorder_swift_fof.py script was meant for that case but dealing with it in the group membership code seems more efficient because we don't need to copy the full snapshot.

**Comment by robjmcgibbon** [comment]
> Just to check that I understand why this is necessary: HBT can run on the new snapshot files generated by the FoF code (e.g. /cosma8/data/dp004/jlvc76/FLAMINGO/FOF/L2800N5040/HYDRO_FIDUCIAL/fof_snapshot), but we can't run SOAP on those same snapshots because not all particle properties are present. Is that correct?

Yes that's right

Storing the FOF IDs in the SOAP membership files also means we will be able to delete the new FOF snapshot files.

**Comment by jchelly** [comment]
In the part of SOAP that reads the snapshot (function read_masked_cells_to_shared_memory() in swift_cells.py) I think we might be reading FOFGroupIDs from both the snapshot and the membership file. If so, we should probably modify it to only read from the membership file when a dataset exists in both places. I'll try running it now to see if that's really happening. There might also be a chance of getting the wrong version of the FOFGroupIDs depending on in what order the tasks complete.

**Comment by jchelly** [comment]
This will now skip reading FOFGroupIDs from the snapshots if it exists in the membership files. It also uses the metadata from the membership files to allocate the array, which would matter if we ever had the same dataset name with different data type or units between the snapshot and membership files.

**Comment by robjmcgibbon** [comment]
Good catch, thanks John. Are you happy for me to merge this into https://github.com/SWIFTSIM/SOAP/tree/merge_halo_finders, or would you prefer for us to finalise the current review of https://github.com/SWIFTSIM/SOAP/pull/71 first? I don't want to add anything in there that will make the comparison with the master branch more difficult.

**Review by jchelly — APPROVED** [review]
I'm happy to merge this now. #71 is already very large so I don't think this makes much difference.

**Pull request merged**
