### PR TITLE
Add support for other halo finders (HBT, Subfind, Rockstar)

### PR DESCRIPTION
**Pull request by jchelly**
Here I've started by modifying the group membership code to read HBTplus output.

SOAP itself will need to be modified to read different halo catalogues too. This should be mostly simple but there is a complication in that HBT and Subfind do not output the distance to the most distant particle so we don't know how large a region to read to get all halo particles. We can probably just read the number of particles in each halo and have the bound/unbound halo property calculations throw an exception and try again with a larger search radius if we find fewer than the expected number of  halo member particles.

We might also want to divide the halo properties to read into halo finder independent quantities which SOAP always needs (e.g. halo centre) and halo finder specific things we just pass through to the output.

### CODE REVIEW

**Comment by MatthieuSchaller** [comment]
Can we make an estimate based on the halo mass the finder reported? e.g. if we know M_200 then we can compute R_200 and then take a reasonable multiple of this.

**Comment by jchelly** [comment]
Yes, we can do something like that to get an initial guess for the search radius. The problem was that up to know we were relying on having a radius that was guaranteed to enclose all of the halo's particles. It will now try again with a larger radius if it doesn't find the expected number of halo member particles. It probably doesn't matter for most halos when we're asking for 3Mpc aperture measurements too.

**Comment by jchelly** [comment]
I also hit the problem that the current code uses the number of unbound particles to decide which calculations to do for which halos (some are skipped for halos with few particles). HBT and Subfind don't output unbound particles for subhalos because any unbound particles are passed to the parent halo to check if they're bound to that.

As a quick fix I'm just using the number of bound particles instead.

**Comment by jchelly** [comment]
For HBT I think it will be necessary to make the group membership code output the number of particles of each type in each halo so we can expand SOAP's search radius until it finds them all. We can't read the number of particles from HBT directly because the count there includes duplicates, where one particle belongs to multiple halos. I've modified the group membership code to assign particles to the HBT halo where their ranking by binding energy is lowest. Joop suggested going for the smallest r/r_virial, but that's much more complicated to do and it's not clear what radius to use for satellite subhalos.

**Comment by jchelly** [comment]
This now runs using HBTplus on L1000N0900/DMO_FIDUCIAL, at least.

**Comment by jchelly** [comment]
This now runs on VR, Subfind and HBT on L1000N0900/HYDRO_FIDUCIAL.

**Comment by robjmcgibbon** [comment]
Closing because of https://github.com/SWIFTSIM/SOAP/pull/71

**Pull request closed without merging**
