### PR TITLE
Fix bug in shared mesh implementation that can cause duplicate particles when mesh contains just one cell

### PR DESCRIPTION
**Pull request by jchelly**
SOAP crashes if a compute node reads a chunk containing exactly one particle of some type because the shared mesh code tries to make a mesh with zero sized cells.

This just sets an arbitrary mesh size in any dimension where the minimum and maximum coordinates are identical. This should handle the single particle case and also cases where we have a small number of particles which happen to be at the same coordinates.

It should address Jeger's crash on L1000N1800/HYDRO_PLANCK_LARGE_NU_VARY snapshot 1:
```
*** EXCEPTION ***
invalid value encountered in true_divide on rank 0

Traceback (most recent call last):
  File "./compute_halo_properties.py", line 497, in <module>
    compute_halo_properties()
  File "./compute_halo_properties.py", line 433, in compute_halo_properties
    metadata = task_queue.execute_tasks(
  File "/cosma/home/dp004/dc-brox1/SOAP_April2023_2/SOAP/task_queue.py", line 195, in execute_tasks
    result.append(task(*args))
  File "/cosma/home/dp004/dc-brox1/SOAP_April2023_2/SOAP/chunk_tasks.py", line 253, in __call__
    mesh[ptype] = shared_mesh.SharedMesh(comm, pos, resolution)
  File "/cosma/home/dp004/dc-brox1/SOAP_April2023_2/SOAP/shared_mesh.py", line 60, in __init__
    cell_idx = np.floor((pos.local-self.pos_min[None,:])/self.cell_size[None,:]).value.astype(np.int32)
  File "/cosma/local/Python/3.10.1/lib/python3.10/site-packages/unyt/array.py", line 1778, in __array_ufunc__
    out_arr = func(
FloatingPointError: invalid value encountered in true_divide
```

### CODE REVIEW

**Comment by jchelly** [comment]
The bug seems to affect snapshots 1-4 of the intermediate res 1Gpc FLAMINGO boxes, except the low sigma8 variation where snapshots 1-5 are affected. Tested by checking that the number of bound star and BH particles in each halo is correct.

**Comment by MatthieuSchaller** [comment]
Is this still work in progress? Do we need more testing?

**Comment by jchelly** [comment]
I can do more testing of this as part of #35. When running on HBTplus or Subfind SOAP will need to know how many bound halo particles to expect so that it knows if the search radius is too small (in VR the initial radius is guaranteed to contain all halo particles). This bug will cause it to either crash due to finding more particles than expected or get stuck continually expanding the radius because it never finds enough.

**Comment by MatthieuSchaller** [comment]
@jchelly I saw you merged master in it. Is it worth me trying this version?

**Comment by jchelly** [comment]
Yes, I think this should work. I added some unit tests which fail in master but pass with this branch. I've also been using it with HBT. In that case it needs to find exactly the expected number of particles to know when to stop increasing the search radius, so if this bug was still a problem it would crash or hang.

**Comment by robjmcgibbon** [comment]
The change looks good to me. I ran it on a small box and checked it produced the same catalog as the master branch. However, io_test.py is failing for me when I try to run it. It throws an error when loading units from cellgrid, but once I fix this I get an MPI-related error. This problem exists on the master branch too, it wasn't introduced by the changes of this PR. I guess it wasn't noticed since the tests which require mpirun (like io_test & shared_mesh) aren't run by pytest. We can make a script which runs all tests when fixing io_test, but maybe that should be a separate PR to this one? If so I'll make an issue

**Comment by MatthieuSchaller** [comment]
Thanks Rob. Let's fix the MPI errors elsewhere if they have not been introduced in this branhc.

**Review by MatthieuSchaller — APPROVED** [review]

**Pull request merged**
