### PR TITLE
Merge Colibre and Flamingo branches

### PR DESCRIPTION
**Pull request by robjmcgibbon**
This is a continuation of https://github.com/SWIFTSIM/SOAP/pull/1. Changes not already mentioned there are below.

Two parameter files are now defined, one for Flamingo and one for Colibre. Each halo type (Aperture, SO, etc..) in the parameter file contains a list of properties to compute. If a property is not listed in the parameter file the default behaviour is to compute it. The halo variations (SO_200crit, SO_500crit, etc...) are also defined in the parameter files.

Documentation is now generated by passing a parameter file, so only properties that will be computed are included in the PDF.

We want to recompute Xray properties for Flamingo but not Colibre, so a parameter has been added to enable this behaviour.

Job scripts are available for running on both Flamingo and Colibre. Running this branch should give exactly the same results for Flamingo as the current master branch. Running this branch will give different results to the colibre branch. These differences are
- SubhaloRankByBoundMass is not calculated for the colibre branch
- The precision of CentreOfMass properties has been changed
- The definition of gas recently heated by AGN has been changed (see https://github.com/SWIFTSIM/SOAP/commit/b6897a41c18acf67c5a7350cc01c5a815822e577)
- We now return intertia tensors instead of just axis lengths

### CODE REVIEW

**Comment by robjmcgibbon** [comment]
TODO for me: Update this branch with changes from https://github.com/SWIFTSIM/SOAP/pull/62

**Comment by jchelly** [comment]
I've tried running this and master on a small FLAMINGO run and I get identical results too, except for one small oddity: in the attribute Parameters/calculations the value  SO_500_crit appears twice in the file generated by this branch.

**Comment by jchelly** [comment]
That might mean that there's a duplicate entry in halo_prop_list, which would cause it to do the calculation twice. It did run slightly slower than master.

**Comment by jchelly** [comment]
I think the issue is probably that we don't need to run the SO_500_crit calculation both with and without the core_excision_fraction parameter. Running it with core_excision_fraction set also computes the non core excised quantities.

**Comment by robjmcgibbon** [comment]
Thanks, I've fixed it. I've also moved the definition of core_excision_fraction to the parameter file, as previously the value of 0.15 was hard-coded.

**Comment by robjmcgibbon** [comment]
I've also found a problem with high redshift snapshots when there's no BH particles present, so I'll work on fixing that now

**Comment by jchelly** [comment]
For high redshift snapshots with missing particle types you can pass it the index of a "reference" snapshot (e.g. z=0) so that it can get the metadata for the missing particle types and set up zero sized arrays instead of having missing arrays. There might still be problems if it's doing things like max() on a zero size array though.

**Comment by jchelly** [comment]
For testing at high redshift we also need the fix from #32. Do you mind if I go ahead and merge it now?

**Comment by robjmcgibbon** [comment]
Sure go ahead

**Comment by jchelly** [comment]
Ok, thanks, I've merged #32 into master. Could you update this branch?

**Comment by robjmcgibbon** [comment]
I've merged https://github.com/SWIFTSIM/SOAP/pull/32, and made a small change so that reference snapshots can be used correctly. This branch now gives the same results as master on L1000N1800/HYDRO_FIDUCIAL snapshot 0002.

**Review by jchelly — APPROVED** [review]
Yes, it all looks ok to me and I'm able to exactly reproduce results from master on FLAMINGO with this branch.

**Pull request merged**
