### PR TITLE
Save AveragedStarFormationRate

### PR DESCRIPTION
**Pull request by robjmcgibbon**
Adding averaged SFR to all halo types. The other minor changes are just from rerunning the formatter.

### CODE REVIEW

**Comment by EvgeniiChaikin** [comment]
Thank you for the update @robjmcgibbon!

I ran this branch on one of my L050m7 runs, and here is the result.

SFR

Each point is a galaxy. The x axis is the instantaneous SFR, and the y axis shows the averaged SFR (100 Myr on the left and 10 Myr on the right). The correlation is tighter in the latter case, as expected.

I am now going to test this run on a z=0.05 snapshot of the L100m7.

**Comment by EvgeniiChaikin** [comment]
Here are two plots from L100m7 confirming that the new fields behave as expected:

gas_SFR_vs_Mstar_per_galaxy

gas_SFR_correlation

**Review by EvgeniiChaikin — APPROVED** [review]
All looks good!

One small note: we could mention in the comment to the new fields that if for a given snapshot, the time passed since the most recent, preceding snapshot is less than the averaging time for the SFR, then the actual averaging time will be smaller (than 10 or 100 Myrs for our case). Namely, it will be equal to the time passed from that preceding snapshot.

**Comment by robjmcgibbon** [comment]
> One small note: we could mention in the comment to the new fields that if for a given snapshot, the time passed since the most recent, preceding snapshot is less than the averaging time for the SFR, then the actual averaging time will be smaller (than 10 or 100 Myrs for our case). Namely, it will be equal to the time passed from that preceding snapshot.

Thanks, I added a comment

**Pull request merged**
