### PR TITLE
Tidy up FLAMINGO job scripts

### LINKED ISSUE #23: L1000N1800 group membership snapshot
The default snapshot number for the L1000N1800 group membership script is 78, however, there are only 77 snapshots for that run.
@jchelly

### PR DESCRIPTION
**Pull request by jchelly**
Here I've tried to set up the FLAMINGO batch scripts so that they will work for Virgo users on Cosma without modifications. Scratch files are written to /snap8/scratch/dp004/${USER}/FLAMINGO/ and compressed output goes to /cosma8/data/dp004/${USER}/FLAMINGO/.

I've also removed the separate hydro and dmo versions of the halo properties scripts to reduce duplication. SOAP is now run with the `--dmo` flag if the simulation name starts with `DMO_`.

I haven't done anything with the compression scripts yet.

(also fixes #23 and includes small test scripts from #15)

This now also adds a top level script that can submit jobs:
```
cd SOAP/scripts/FLAMINGO
./submit_jobs.sh --run=L0100N0180/HYDRO_FIDUCIAL --snapshots=0-5 \
  --membership --soap --compress-soap --compress-membership
```
This will add dependencies between jobs where necessary.

### CODE REVIEW

**Comment by jchelly** [comment]
For L0100N0180 this now includes a script that submits a set of array jobs with dependencies to compute group membership, run SOAP, and then compress the output for a specified range of snapshots.

**Comment by jemme07** [comment]
Can this be merged now?

**Comment by jchelly** [comment]
It would be good to hear that this works for someone other than me before we merge it. Some of the time limits probably need to be increased too.

**Comment by MatthieuSchaller** [comment]
@jemme07 ?

(I have been using my own older scripts....)

**Comment by MatthieuSchaller** [comment]
@jemme07 any updates on this?

**Comment by jemme07** [comment]
> @jemme07 any updates?

I have been using my own olda scripts as well, but I can test it on one snap.

**Comment by MatthieuSchaller** [comment]
Any news?

**Comment by MatthieuSchaller** [comment]
This should be merged. @jemme07 and @jchelly any final words?

**Comment by jchelly** [comment]
I'm not sure anyone else is using this version of the scripts, but they work for me.

**Comment by MatthieuSchaller** [comment]
Let's merge this for the record then.

**Review by MatthieuSchaller — APPROVED** [review]

**Pull request merged**
