### PR TITLE
Joey xrays

### PR DESCRIPTION
**Pull request by Joeybraspenning**
Pull request to the correct repository. This implements x-ray implementation in SOAP

### CODE REVIEW

**Comment by Joeybraspenning** [comment]
Running into the problem that the SOAP units are not what the x-ray interpolation expects. It expects units as in the snapshots (so Msun, or Mpc, or even in cgs), but instead there seem to be placeholder units
`units='snap_mass/(a**3*snap_length**3)'`
Is there a way to extract the physical units from this?

**Comment by jchelly** [comment]
It might be best to convert everything to the units you need, strip the units, do your calculation, then assign units at the end. E.g. to get positions in comoving Mpc as a numpy array with no units
```
pos_in_comoving_mpc = pos_in_snap_units.to("a*swift_mpc").value
```

**Comment by Joeybraspenning** [comment]
With that fixed, the x-ray code seems to work. But I again run into the issue with the I_tensor
Is there already a fix for this? I should be up to date with master.

`  File "/cosma8/data/dp004/dc-bras1/SOAP/SOAP/kinematic_properties.py", line 139, in get_axis_lengths
    Itensor[:, i, j] *= position[:, i] * position[:, j]
  File "/cosma/home/dp004/dc-bras1/.local/lib/python3.10/site-packages/unyt/array.py", line 1734, in __setitem__
    value = value.to(self.units)
  File "/cosma/home/dp004/dc-bras1/.local/lib/python3.10/site-packages/unyt/array.py", line 947, in to
    return self.in_units(units, equivalence=equivalence, **kwargs)
  File "/cosma/home/dp004/dc-bras1/.local/lib/python3.10/site-packages/unyt/array.py", line 874, in in_units
    (conversion_factor, offset) = self.units.get_conversion_factor(
  File "/cosma/home/dp004/dc-bras1/.local/lib/python3.10/site-packages/unyt/unit_object.py", line 694, in get_conversion_factor
    return _get_conversion_factor(self, other_units, dtype)
  File "/cosma/home/dp004/dc-bras1/.local/lib/python3.10/site-packages/unyt/unit_object.py", line 939, in _get_conversion_factor
    raise UnitConversionError(
unyt.exceptions.UnitConversionError: Cannot convert between 'snap_length**2' (dim '(length)**2') and 'dimensionless' (dim '1').`

**Comment by jchelly** [comment]
The fix for that one was merged into [SOAP_additions_joey_roi](https://github.com/SWIFTSIM/SOAP/tree/SOAP_additions_joey_roi) so it's not in master yet.

**Comment by MatthieuSchaller** [comment]
Here is the suggestion:

1-  Make the `XRayCalculator` class read the data in the constructor.
2-  Discard the tables entries we don't need for that redshift.
3-  Create an XRayCalculator object in `compute_halo_properties()`, say just before reading the VR content.
4- Pass the object to the `ChunkTaskList` in the constructor who keeps it as a self.
5- The ChunkTaskList then passes the object down all the way to where we use it now.

**Comment by MatthieuSchaller** [comment]
Next improvement only read on rank 0 and then broadcast. 

Let's try first without that as it is then just "pure" python. The MPI bits are never fun.

**Comment by MatthieuSchaller** [comment]
@jchelly would you agree with that? Especially the placement of the construction of the `XRayCalculator` object?

**Comment by jchelly** [comment]
The ChunkTaskList send tasks between MPI ranks so it might be a little easier to add the XrayCalculator as an argument passed to each individual chunk task. To do that you would add the XrayCalculator as an argument to `ChunkTask.__call_()` in chunk_tasks.py and also add it to the task_args list in compute_halo_properties.py. Then every time a chunk task runs the XrayCalculator will be passed to it.

Creating the XrayCalculator on one rank and broadcasting isn't too hard:
```
if comm_rank == 0:
  xray_calculator = XrayCalculator(...)
else:
  xray_calculator = None
xray_calculator = comm.bcast(xray_calculator)
```

**Comment by Joeybraspenning** [comment]
I've pushed a working version (without MPI) which is now only 40% slower than without x-rays.
MPI doesn't work yet as it would also have to pass the table itself between ranks and it's telling me that h5py objects can't be pickled.

`Traceback (most recent call last):
  File "./compute_halo_properties.py", line 496, in <module>
    compute_halo_properties()
  File "./compute_halo_properties.py", line 359, in compute_halo_properties
    xray_calculator = comm_world.bcast(xray_calculator)
  File "mpi4py/MPI/Comm.pyx", line 1569, in mpi4py.MPI.Comm.bcast
  File "mpi4py/MPI/msgpickle.pxi", line 721, in mpi4py.MPI.PyMPI_bcast
  File "mpi4py/MPI/msgpickle.pxi", line 145, in mpi4py.MPI.pickle_dump
  File "mpi4py/MPI/msgpickle.pxi", line 131, in mpi4py.MPI.cdumps
  File "/cosma/local/Python/3.10.1/lib/python3.10/site-packages/h5py/_hl/base.py", line 368, in __getnewargs__
    raise TypeError("h5py objects cannot be pickled")
TypeError: h5py objects cannot be pickled`

**Comment by MatthieuSchaller** [comment]
Ok, great. I think with John's solution above it will work.

**Comment by Joeybraspenning** [comment]
Running on L0100N0180 works, but for L0200N0360 (both HYDRO_FIDUCIAL and HYDRO_JETS) it crashes with this error message. Same error appears when using SOAP_additions_joey_roi. 
`self.gas_densities` is not a new thing, that already existed before. Not sure why it's suddenly a None type object, and also not sure why it does work on the 100Mpc.

`*** EXCEPTION ***
'NoneType' object is not subscriptable on rank 108

Traceback (most recent call last):
  File "./compute_halo_properties.py", line 480, in <module>
    compute_halo_properties()
  File "./compute_halo_properties.py", line 417, in compute_halo_properties
    metadata = task_queue.execute_tasks(
  File "/cosma8/data/dp004/dc-bras1/SOAP_2/SOAP/task_queue.py", line 195, in execute_tasks
    result.append(task(*args))
  File "/cosma8/data/dp004/dc-bras1/SOAP_2/SOAP/chunk_tasks.py", line 265, in __call__
    total_time, task_time, nr_left, nr_done = process_halos(comm, cellgrid.snap_unit_registry, data, mesh,
  File "/cosma8/data/dp004/dc-bras1/SOAP_2/SOAP/halo_tasks.py", line 278, in process_halos
    halo_result = process_single_halo(
  File "/cosma8/data/dp004/dc-bras1/SOAP_2/SOAP/halo_tasks.py", line 118, in process_single_halo
    halo_prop.calculate(
  File "/cosma8/data/dp004/dc-bras1/SOAP_2/SOAP/SO_properties.py", line 1571, in calculate
    val = getattr(part_props, name)
  File "/cosma8/data/dp004/dc-bras1/SOAP_2/SOAP/lazy_properties.py", line 18, in _lazy_property
    setattr(self, attr_name, fn(self))
  File "/cosma8/data/dp004/dc-bras1/SOAP_2/SOAP/SO_properties.py", line 987, in SpectroscopicLikeTemperature
    self.gas_densities[self.gas_selection_xray_temperature]
TypeError: 'NoneType' object is not subscriptable`

**Comment by MatthieuSchaller** [comment]
@Joeybraspenning The functions in the xray calculator need some better docstrings. 

Also, we should run `black` on this and probably merge master into it too as there are unrelated changes appearing in the diff currently.

**Comment by Joeybraspenning** [comment]
Trying to build a test, I encountered a new problem. We want to create new fields which don't exist in the snapshots (restframe x-rays as opposed to observed-frame). However, when I simply try to create them when calculating the x-rays and add the functions and properties in the right places, SOAP tells me it can't find the required dataset in the input file, which probably means it's looking in the snapshots but can't find it.
What would be the best way to fix this?

`Traceback (most recent call last):
  File "./compute_halo_properties.py", line 497, in <module>
    compute_halo_properties()
  File "./compute_halo_properties.py", line 433, in compute_halo_properties
    metadata = task_queue.execute_tasks(
  File "/cosma8/data/dp004/dc-bras1/SOAP/SOAP/task_queue.py", line 195, in execute_tasks
    result.append(task(*args))
  File "/cosma8/data/dp004/dc-bras1/SOAP/SOAP/chunk_tasks.py", line 212, in __call__
    data = cellgrid.read_masked_cells_to_shared_memory(properties, mask, comm, max_ranks_reading)
  File "/cosma8/data/dp004/dc-bras1/SOAP/SOAP/swift_cells.py", line 512, in read_masked_cells_to_shared_memory
    raise Exception(
Exception: Can't find required dataset XrayLuminositiesRestframe in input file(s)!`

**Comment by MatthieuSchaller** [comment]
It would need to point to the newly created arrays that have just been computed from the tables.

**Comment by Joeybraspenning** [comment]
yes, but not sure how to convince SOAP that those are coming from a snapshot such that it doesn't throw this exception

**Comment by MatthieuSchaller** [comment]
How about changing `SO_properties.py` and add the equivalent to `gas_xraylum()` and make it return the arrays that were created?

**Comment by jchelly** [comment]
Bert added a mechanism where SOAP computes which particle properties to read from the snapshot based on what halo properties are being computed. I guess we need to figure out how to make an exception for particle properties which we compute rather than read.

**Comment by jchelly** [comment]
I was mistaken about dependencies - I think the automatic dependencies are only in the COLIBRE branch.

To stop it trying to read a dataset all you need to do is avoid adding it to particle_properties list in the SOProperties (or equivalent for apertures etc) class. particle_properties lists what quantities need to be read in for each type of aperture. I guess the version you're testing must have some commits you didn't push yet?

**Comment by Joeybraspenning** [comment]
Just pushed the version which is what I'm running now.
Removing the restframes from the particle_properties list just gives a new error:

`  File "/cosma8/data/dp004/dc-bras1/SOAP/SOAP/SO_properties.py", line 1652, in calculate
    SO[name].shape == val.shape
AttributeError: 'function' object has no attribute 'shape'`

**Comment by Joeybraspenning** [comment]
I think one of these tests needs either a custom exception, or we need to somehow do the test in such a way that snapshot properties are treated different from SOAP-calculated properties

**Comment by MatthieuSchaller** [comment]
Is  it a test that is failing now or the actual code on a snapshot?

**Comment by Joeybraspenning** [comment]
the code

**Comment by Joeybraspenning** [comment]
There is this assertion which prevents me from removing them from the particle_properties
`File "/cosma8/data/dp004/dc-bras1/SOAP/SOAP/SO_properties.py", line 1652, in calculate SO[name].shape == val.shape AttributeError: 'function' object has no attribute 'shape'`

But then this check prevents me from adding them to particle_properties
`File "/cosma8/data/dp004/dc-bras1/SOAP/SOAP/chunk_tasks.py", line 212, in __call__ data = cellgrid.read_masked_cells_to_shared_memory(properties, mask, comm, max_ranks_reading) File "/cosma8/data/dp004/dc-bras1/SOAP/SOAP/swift_cells.py", line 512, in read_masked_cells_to_shared_memory raise Exception( Exception: Can't find required dataset XrayLuminositiesRestframe in input file(s)!`.

So we're stuck where we need them to pass a check, but also need them gone for another check

**Comment by MatthieuSchaller** [comment]
and in swift_cells.py, we'd need to escape these entries. Might mean we need to maintain somewhere a list of named properties that we don't read.
Then here, do something special if the entry is in the list.

**Comment by MatthieuSchaller** [comment]
This should now work.

**Comment by MatthieuSchaller** [comment]
For the record, we needed a `lazy_property`

**Comment by Joeybraspenning** [comment]
I believe this is fully up-to-date including all the changes from SOAP_additions_joey_roi.
The only unresolved issue is the table path. It is now hard-coded to point to a table in one of my folders (who's perpetuity I can hardly guarantee...)

**Review by jchelly — APPROVED** [review]
I think I'm happy to leave the table hard coded for now. We should switch to using a parameter file but that can be done when the colibre branch is merged.

**Pull request merged**
